Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2022-09, with the labels that each got.

#101 Drop collections of a local DB before tests
  initialization/database.js
Labels: Backend, tests

#103 Use params instead of body for the reset token
  controllers/auth.js
  docs/auth/auth-schema.yaml
  docs/auth/auth.yaml
  routes/auth.js
  validation/schemas/resetPassword.js
Labels: Backend, feature

#88 Wrote test for admin controller
  test/integration/controllers/admin.spec.js
Labels: Backend, tests

#110 add tests for email controller
  test/integration/controllers/email.spec.js
Labels: Backend, tests

#108 write tests for refresh, sendPass, resetPass
  test/integration/controllers/auth.spec.js
Labels: Backend, tests

#107 Bugfix/106/Invalid token names
  consts/errors.js
  services/token.js
Labels: bug, Backend

#104 refactored user service and fixed error naming
  consts/errors.js
  controllers/user.js
  cron-jobs/checkForLastLogin.js
  docs/admin/admin.yaml
  docs/auth/auth-schema.yaml
  docs/auth/auth.yaml
  docs/user/user-schema.yaml
  docs/user/user.yaml
  routes/user.js
  services/admin.js
  services/auth.js
  services/user.js
  test/integration/controllers/admin.spec.js
  test/integration/controllers/auth.spec.js
  utils/mailer.js
Labels: Backend

#112 Add translation for the templates
  .husky/pre-push
  consts/errors.js
  consts/validation.js
  controllers/auth.js
  controllers/email.js
  emails/en/confirm-email.pug
  emails/en/index.pug
  emails/en/long-time-without-login.pug
  emails/en/reset-password.pug
  emails/index.js
  emails/ua/confirm-email.pug
  emails/ua/index.pug
  emails/ua/long-time-without-login.pug
  emails/ua/reset-password.pug
  middlewares/language.js
  routes/auth.js
  routes/email.js
  services/auth.js
  services/email.js
  test/unit/middlewares/language.spec.js
Labels: Backend, email, feature

#116 Uncomment pre push tests
  .husky/pre-push
Labels: Backend

#120 user returns with a role value instead of a role object
  services/user.js
Labels: bug, Backend

#128 logout returns 204, fixed tests
  controllers/auth.js
  services/auth.js
  test/integration/controllers/auth.spec.js
Labels: Backend

#126 deleted example
  consts/errors.js
  controllers/example.js
  docs/example-schema.yaml
  docs/example.yaml
  models/example.js
  routes/example.js
  routes/index.js
  test/integration/controllers/example.spec.js
Labels: Backend

#119 use the accept-lang header for the lang detection
  cron-jobs/checkForLastLogin.js
  middlewares/language.js
  models/user.js
  services/auth.js
  services/user.js
  test/unit/middlewares/language.spec.js
Labels: Backend, feature

#124 Add successful reset password email
  consts/emailSubject.js
  controllers/auth.js
  emails/en/sucessful-password-reset.pug
  emails/index.js
  emails/ua/sucessful-password-reset.pug
  routes/auth.js
  services/auth.js
  test/integration/controllers/auth.spec.js
Labels: Backend, email, feature

#98 Created cron job for deleting unverified users and refactored existin…
  cron-jobs/checkForLastLogin.js
  cron-jobs/removeUnverifiedUsers.js
  cron-jobs/scheduledCronJobs.js
  initialization/serverSetup.js
  services/token.js
  test/unit/cron-jobs/removeUnverifiedUsers.spec.js
  test/unit/cron-jobs/scheduledCronJobs.spec.js
Labels: Backend

#132 added int test for user controller
  controllers/auth.js
  services/user.js
  test/integration/controllers/user.spec.js
Labels: Backend, tests
