Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2022-08, with the labels that each got.

#26 added validation middleware for check
  consts/errors.js
  middlewares/validation.js
  routes/auth.js
  utils/validationHelper.js
  validation/schemas/signup.js
Labels: enhancement, Backend

#43 Feature/37/reset password endpoint
  consts/auth.js
  consts/emailSubject.js
  consts/errors.js
  controllers/auth.js
  docs/auth/auth-schema.yaml
  docs/auth/auth.yaml
  emails/index.js
  models/token.js
  routes/auth.js
  services/auth.js
  services/token.js
  utils/passwordHelper.js
Labels: Backend, email

#47 Feature/45/validation for all endpoints
  consts/errors.js
  consts/validation.js
  controllers/auth.js
  routes/auth.js
  services/auth.js
  utils/passwordHelper.js
  utils/validationHelper.js
  validation/schemas/forgotPassword.js
  validation/schemas/login.js
  validation/schemas/resetPassword.js
  validation/schemas/signup.js
Labels: Backend

#46 added role model, updated user model, seeded roles and superadmin user to the DB
  app.js
  consts/auth.js
  consts/errors.js
  consts/seed.js
  models/role.js
  models/user.js
  seed/checkRoleExistence.js
  seed/checkUserExistence.js
  seed/seedRole.js
  seed/seedSuperAdmin.js
  services/auth.js
Labels: Backend

#49 Feature/45/Docs for responses
  docs/auth/auth.yaml
  docs/error/error-schema.yaml
Labels: documentation, Backend

#48 Added template for reset password
  emails/css/index.css
  emails/index.pug
  emails/reset-password.pug
Labels: Backend, email

#59 added initialization and configs, removed configs from consts
  app.js
  configs/config.js
  consts/gmailAuth.js
  consts/seed.js
  initialization/database.js
  initialization/initialization.js
  logger/logger.js
  seed/seedSuperAdmin.js
  services/token.js
  utils/emailService.js
  utils/mailer.js
Labels: Backend

#57 Feature/53/moving logic to services
  consts/validation.js
  controllers/admin.js
  controllers/auth.js
  controllers/user.js
  docs/user/user.yaml
  services/admin.js
  services/user.js
Labels: Backend

#58 Feature/50/first login endpoint
  models/user.js
  services/auth.js
Labels: Backend

#60 added text line to the confirm-email template about expiration
  emails/confirm-email.pug
Labels: Backend, email

#64 added confirm token, updated signup/login and swagger docs
  configs/config.js
  consts/auth.js
  consts/errors.js
  controllers/auth.js
  docs/auth/auth.yaml
  emails/confirm-email.pug
  models/token.js
  models/user.js
  package-lock.json
  package.json
  routes/auth.js
  seed/seedSuperAdmin.js
  services/admin.js
  services/auth.js
  services/token.js
  services/user.js
Labels: Backend, Auth

#63 added middleware that validates incoming id
  consts/errors.js
  middlewares/idValidation.js
  routes/admin.js
  routes/example.js
  routes/user.js
Labels: Backend

#77 Feature/76/fixed refresh token
  configs/config.js
  controllers/auth.js
Labels: Backend

#67 Bugfix/53/Fix role querying
  services/admin.js
Labels: bug, Backend

#75 Bugfix/74/Remove login validation
  validation/schemas/login.js
Labels: Backend

#79 changed validation order in login
  services/auth.js
Labels: bug, Backend

#68 Feature/65/Migrate tests to Jest
  .eslintrc.json
  .gitignore
  jest.config.js
  logger/logger.js
  package-lock.json
  package.json
  test/helper.js
  test/unit/controllers/example.spec.js
Labels: Backend, tests

#80 Feature/70/Refactored refresh access token endpoint
  configs/config.js
  consts/errors.js
  controllers/auth.js
  docs/auth/auth-schema.yaml
  docs/auth/auth.yaml
  routes/auth.js
  services/auth.js
  services/user.js
Labels: Backend

#87 Bugfix/86/Remove special symbols validation
  consts/errors.js
  consts/validation.js
Labels: bug, Backend

#97 added send-email endpoint
  consts/errors.js
  controllers/email.js
  cron-jobs/checkForLastLogin.js
  routes/email.js
  routes/index.js
  services/auth.js
  services/email.js
  utils/mailer.js
Labels: Backend, email

#90 added error stack tracing, changed print format
  logger/logger.js
Labels: Backend

#93 removed unnesessary space in pug
  emails/confirm-email.pug
  emails/css/index.css
  emails/index.js
  emails/index.pug
  emails/long-time-without-login.pug
  emails/reset-password.pug
Labels: Backend, email

#100 Feature/82/auth controller testing
  consts/errors.js
  package.json
  services/auth.js
  test/helpers.js
  test/integration/controllers/auth.spec.js
  test/setup.js
Labels: Backend, tests
