Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2022-10, with the labels that each got.

#152 Feature/139/Create review model, route and swagger
  consts/errors.js
  controllers/review.js
  docs/review/review-schema.yaml
  docs/review/review.yaml
  models/review.js
  routes/index.js
  routes/review.js
Labels: documentation, Backend, feature

#153 added categories model and seeded
  consts/categories.js
  initialization/serverSetup.js
  models/category.js
  seed/checkCategoryExistence.js
  seed/seedCategory.js
Labels: Backend, predecessor, feature

#157 Feature/137/tutor model route swagger
  consts/validation.js
  controllers/tutor.js
  docs/tutor/tutor-schema.yaml
  docs/tutor/tutor.yaml
  models/tutor.js
  routes/index.js
  routes/tutor.js
Labels: Backend, feature

#156 created student model with route and swagger docs
  controllers/student.js
  docs/student/student-schema.yaml
  docs/student/student.yaml
  models/student.js
  routes/index.js
  routes/student.js
Labels: Backend, predecessor, feature

#151 Feature/134/admin
  consts/validation.js
  controllers/admin.js
  docs/admin/admin-schema.yaml
  docs/admin/admin.yaml
  models/admin.js
  routes/admin.js
  test/integration/controllers/admin.spec.js
Labels: documentation, Backend, predecessor
