Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2023-12, with the labels that each got.

#658 Added enrolledOffer filed to updateOffer and gave possibility to update this field for student
  models/offer.js
  services/offer.js
  validation/services/offer.js
Labels: Backend, feature

#656 Added settings for quiz
  consts/validation.js
  docs/quiz/quiz-schema.yaml
  docs/quiz/quiz.yaml
  models/quiz.js
  services/quiz.js
Labels: Backend

#668 Changed swagger for Users and Comments
  docs/comment/comment.yaml
  docs/review/review-schema.yaml
  docs/user/user.yaml
Labels: documentation, Backend

#672 Expanded the resource type field, added needed fields to edit course
  consts/validation.js
  models/attachment.js
  models/lesson.js
  models/question.js
  models/quiz.js
  services/course.js
Labels: enhancement, Backend

#685 Update README.md
  README.md
Labels: documentation

#663 Updated getQuestionById service and added docs for it in Swagger
  docs/questions/question.yaml
  services/question.js
Labels: Backend

#665 Fixed active offers number
  models/offer.js
Labels: Backend

#683 Added additional fields for search courses
  controllers/course.js
  services/course.js
Labels: Backend

#670 Fixed quiz view types after created new questions
  services/quiz.js
Labels: bug, Backend

#666 Added 400 status code for patch users id
  docs/user/user.yaml
Labels: bug, Backend, error

#684 Refactored token and checkForLastLogin tests
  test/unit/cron-jobs/checkForLastLogin.spec.js
  test/unit/services/token.spec.js
Labels: Backend, tests

#667 fixed swagger
  docs/lesson/lesson.yaml
Labels: bug, Backend

#677 Refactored "lesson", "message", "notification" and "quiz" tests
  docs/quiz/quiz-schema.yaml
  docs/quiz/quiz.yaml
  models/quiz.js
  test/integration/controllers/lesson.spec.js
  test/integration/controllers/message.spec.js
  test/integration/controllers/notification.spec.js
  test/integration/controllers/quiz.spec.js
Labels: Backend, tests
