Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2023-05, with the labels that each got.

#344 Fix sorting users by status in table
  utils/users/createAggregateOptions.js
Labels: Backend

#341 Deleting all offers that are related to deleted user
  models/user.js
Labels: Backend, feature

#348 Added sorting categories by qty of offers
  services/category.js
Labels: Backend, feature

#355 Fixed totalOffers in subjects and categories
  models/offer.js
Labels: bug, Backend

#363 Fixed errors appeared after running tests few times
  test/integration/controllers/adminInvitation.spec.js
  test/integration/controllers/auth.spec.js
  test/integration/controllers/category.spec.js
  test/integration/controllers/email.spec.js
  test/integration/controllers/offer.spec.js
  test/integration/controllers/review.spec.js
  test/integration/controllers/subject.spec.js
  test/integration/controllers/user.spec.js
  test/setup.js
  utils/testUserAuth.js
Labels: Backend

#360 Added capitalizing for the first letter of the subject
  services/subject.js
  utils/capitalizeFirstLetter.js
Labels: Backend

#359 Fixed model of user and swagger
  controllers/user.js
  docs/user/user.yaml
  models/user.js
  services/user.js
  test/integration/controllers/user.spec.js
  validation/services/user.js
Labels: Backend, feature

#356 Added capitalizing letters for category in seeds
  consts/categories.js
Labels: Backend

#377 Implemented FAQ for users and offers
  controllers/offer.js
  docs/offer/offer-schema.yaml
  docs/offer/offer.yaml
  docs/user/user-schema.yaml
  docs/user/user.yaml
  models/offer.js
  models/user.js
  services/offer.js
  services/user.js
  validation/services/offer.js
  validation/services/user.js
Labels: Backend

#376 Fixed review and offer models
  docs/offer/offer-schema.yaml
  docs/offer/offer.yaml
  docs/review/review.yaml
  models/offer.js
  models/review.js
  services/offer.js
  services/review.js
  utils/offers/offerAggregateOptions.js
Labels: Backend

#378 Bug/min max price fix
  test/integration/controllers/category.spec.js
  test/integration/controllers/offer.spec.js
Labels: Backend

#386 Fix review tests
  models/user.js
  test/integration/controllers/review.spec.js
Labels: Backend

#380 Implemented functionality to get all users cooperations
  controllers/cooperation.js
  docs/user/user.yaml
  routes/cooperation.js
  routes/user.js
  services/cooperation.js
  utils/cooperations/coopsAggregateOptions.js
Labels: Backend, feature

#379 Added sorting and pagination for cooperations
  consts/errors.js
  controllers/cooperation.js
  models/cooperation.js
  models/offer.js
  models/user.js
  services/cooperation.js
  utils/cooperations/coopsAggregateOptions.js
Labels: Backend, feature

#389 additinal offer filtering and route for getting all offers by user id
  docs/user/user.yaml
  models/offer.js
  routes/user.js
  services/offer.js
  test/integration/controllers/offer.spec.js
  utils/offers/offerAggregateOptions.js
  utils/testUserAuth.js
Labels: Backend, feature

#375 Create new category
  controllers/category.js
  docs/category/category.yaml
  models/category.js
  routes/category.js
  services/category.js
  test/integration/controllers/category.spec.js
  utils/capitalizeFirstLetter.js
Labels: Backend, feature

#388 Fixed sorting subjects and categories. Limit increased for JSON
  initialization/initialization.js
  services/category.js
  services/subject.js
Labels: Backend, feature
