Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2023-03, with the labels that each got.

#220 migrated to a new node v
  package-lock.json
Labels: Backend

#215 Added aggregation for review
  services/review.js
  utils/reviews/reviewAggregation.js
Labels: Backend

#225 added virtuals for reviews and /reviews endpoint for user
  controllers/review.js
  jest.config.js
  models/user.js
  routes/review.js
  routes/user.js
  services/review.js
  services/user.js
Labels: Backend, feature

#224 Added status to getUsers
  consts/validation.js
  models/user.js
  services/user.js
  utils/users/createAggregateOptions.js
Labels: bug, Backend

#233 added review calc for each rating
  services/user.js
  utils/reviews/reviewStatsAggregation.js
Labels: enhancement, Backend

#217 added tests for offer entity controller
  models/offer.js
  routes/offer.js
  test/integration/controllers/offer.spec.js
Labels: Backend

#244 split endpoints by a role, added aggregation for review stats
  controllers/review.js
  controllers/user.js
  models/review.js
  models/user.js
  routes/user.js
  services/review.js
  services/user.js
  utils/reviews/reviewAggregation.js
  utils/reviews/reviewStatsAggregation.js
Labels: enhancement, Backend

#245 refactored subject test
  models/subject.js
  test/integration/controllers/subject.spec.js
Labels: Backend, feature

#227 Refactored review, added population and filtration
  controllers/review.js
  docs/review/review-schema.yaml
  docs/review/review.yaml
  models/offer.js
  models/review.js
  models/user.js
  services/review.js
  test/integration/controllers/review.spec.js
  utils/getMatchOptions.js
Labels: Backend

#249 Deleted all files related to admin
  controllers/admin.js
  docs/admin/admin-schema.yaml
  docs/admin/admin.yaml
  routes/admin.js
  routes/index.js
  services/admin.js
  test/integration/controllers/admin.spec.js
  utils/getAdminsQuery.js
Labels: Backend

#248 added my profile endpoint
  controllers/user.js
  middlewares/setCurrentUserId.js
  middlewares/setCurrentUserIdAndRole.js
  routes/offer.js
  routes/review.js
  routes/user.js
Labels: Backend, feature

#257 Refactored and fixed email test
  test/integration/controllers/email.spec.js
Labels: Backend, tests

#262 added aggregation pipeline to calc avg and total reviews
  controllers/review.js
  models/offer.js
  models/review.js
  models/user.js
  routes/user.js
  utils/reviews/reviewStatsAggregation.js
Labels: enhancement, Backend

#260 Added file for models in consts
  consts/models.js
  models/adminInvitation.js
  models/category.js
  models/offer.js
  models/review.js
  models/subject.js
  models/token.js
  models/user.js
Labels: enhancement, good first issue, Backend

#253 Refactored adminInvitation test
  test/integration/controllers/adminInvitation.spec.js
Labels: Backend, tests

#264 Validation messages for enums
  consts/validation.js
  models/offer.js
  models/user.js
Labels: enhancement, good first issue, Backend

#272 Fix SonarCloud Coverage
  .github/workflows/main.yaml
  .gitignore
  sonar-project.properties
Labels: bug, Backend, devOps

#252 Implemented cooperation model, route, docs
  consts/errors.js
  consts/validation.js
  controllers/cooperation.js
  docs/cooperation/cooperation.schema.yaml
  docs/cooperation/cooperation.yaml
  models/cooperation.js
  routes/cooperation.js
  routes/index.js
  services/cooperation.js
Labels: Backend, feature

#278 Updated swagger for user model
  docs/user/user-schema.yaml
  docs/user/user.yaml
  utils/reviews/reviewStatsAggregation.js
Labels: documentation, Backend

#287 Fixed Cron jobs
  cron-jobs/checkForLastLogin.js
Labels: Backend, error, Prio

#288 Fix middleware naming in cooperation route
  routes/cooperation.js
Labels: Backend

#308 added route for getting all category names
  controllers/category.js
  routes/category.js
  services/category.js
Labels: Backend, feature

#300 Added /subjects/names route
  controllers/subject.js
  docs/category/category.yaml
  routes/category.js
  routes/subject.js
  services/subject.js
Labels: Backend, Prio

#304 feature/289/test-for-categories-page
  test/integration/controllers/category.spec.js
Labels: Backend

#303 Implemented filtering for subject
  controllers/subject.js
  services/subject.js
Labels: enhancement, Backend, Prio

#315 refactor getCategoriesNames endpoint
  services/category.js
Labels: Backend

#290 added nested route for offers
  consts/errors.js
  consts/validation.js
  controllers/offer.js
  controllers/user.js
  docs/auth/auth.yaml
  docs/category/category.yaml
  docs/cooperation/cooperation.yaml
  docs/offer/offer.yaml
  docs/review/review.yaml
  docs/subject/subject.yaml
  docs/user/user.yaml
  middlewares/entityValidation.js
  models/user.js
  routes/category.js
  routes/cooperation.js
  routes/offer.js
  routes/review.js
  routes/subject.js
  routes/user.js
  services/auth.js
  services/category.js
  services/cooperation.js
  services/offer.js
  services/review.js
  services/subject.js
  services/user.js
  test/integration/controllers/auth.spec.js
  test/integration/controllers/category.spec.js
  test/integration/controllers/offer.spec.js
  test/integration/controllers/review.spec.js
  test/integration/controllers/subject.spec.js
  test/integration/controllers/user.spec.js
Labels: enhancement, Backend
