Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2023-10, with the labels that each got.

#591 Create resource category endpoint
  controllers/resourcesCategory.js
  docs/resourcesCategory/resourcesCategory.yaml
  routes/resourcesCategory.js
  services/resourcesCategory.js
  test/integration/controllers/resourcesCategory.spec.js
Labels: Backend, feature

#594 implemented update for resource category
  controllers/resourcesCategory.js
  docs/resourcesCategory/resourcesCategory.schema.yaml
  docs/resourcesCategory/resourcesCategory.yaml
  routes/resourcesCategory.js
  services/resourcesCategory.js
  test/integration/controllers/resourcesCategory.spec.js
Labels: Backend, feature

#606 changed patch route and model for attachments
  controllers/attachment.js
  docs/attachments/attachment.yaml
  docs/attachments/attachments-schema.yaml
  docs/resourcesCategory/resourcesCategory.yaml
  models/attachment.js
  services/attachment.js
  services/resourcesCategory.js
Labels: Backend, feature

#603 Fixed category field for resouces in models and yaml schemas
  docs/attachments/attachment.yaml
  docs/attachments/attachments-schema.yaml
  docs/lesson/lesson-schema.yaml
  docs/lesson/lesson.yaml
  docs/questions/question.schema.yaml
  docs/questions/question.yaml
  docs/questions/questions.yaml
  docs/quiz/quiz-schema.yaml
  docs/quiz/quiz.yaml
  models/lesson.js
  models/question.js
  models/quiz.js
  test/integration/controllers/lesson.spec.js
  test/integration/controllers/quiz.spec.js
Labels: Backend

#608 Changed Question and Quiz according to diagram
  docs/questions/question.schema.yaml
  docs/questions/question.yaml
  docs/quiz/quiz-schema.yaml
  docs/quiz/quiz.yaml
  models/question.js
  models/quiz.js
  services/question.js
  test/integration/controllers/question.spec.js
  test/integration/controllers/quiz.spec.js
Labels: Backend

#531 Feature/delete test
  controllers/quiz.js
  docs/quiz/quiz.yaml
  routes/quiz.js
  services/quiz.js
Labels: Backend, feature

#589 Delete resource-category endpoint
  controllers/resourcesCategory.js
  docs/resourcesCategory/resourcesCategory.yaml
  routes/resourcesCategory.js
  services/resourcesCategory.js
Labels: Backend, feature

#614 Implemented delete for current user endpoint
  controllers/chat.js
  docs/chat/chat.yaml
  models/chat.js
  routes/chat.js
  services/chat.js
  test/integration/controllers/chat.spec.js
Labels: enhancement, Backend, feature

#618 Added contributing files
  CONTRIBUTING.md
  CONTRIBUTING_UA.md
Labels: Backend

#600 Fixed issues to response question data and category
  controllers/attachment.js
  controllers/lesson.js
  controllers/question.js
  controllers/quiz.js
  cron-jobs/removeUnverifiedUsers.js
  services/auth.js
  services/lesson.js
  services/quiz.js
  services/token.js
Labels: Backend, feature
