Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2023-04, with the labels that each got.

#313 Refactor categories and subjects
  controllers/category.js
  controllers/subject.js
  models/category.js
  routes/category.js
  services/subject.js
  test/integration/controllers/category.spec.js
Labels: Backend

#318 Added hooks for counting total offers
  models/offer.js
Labels: enhancement, Backend, Prio

#319 Added color field to category
  consts/categories.js
  docs/category/category-schema.yaml
  docs/category/category.yaml
  docs/review/review.yaml
  models/category.js
  test/integration/controllers/category.spec.js
Labels: Backend, feature, Prio

#321 Refactored category model and service
  consts/errors.js
  models/category.js
  models/cooperation.js
  models/offer.js
  models/review.js
  models/subject.js
  models/user.js
  services/category.js
Labels: enhancement, Backend

#311 feature/swagger-add-new-route-min-max-prices
  docs/category/category.yaml
Labels: documentation, Backend, Prio

#307 feature/offer-endpoint-min-max
  controllers/category.js
  routes/category.js
  services/category.js
  test/integration/controllers/offer.spec.js
  utils/categories/conditionCreator.js
Labels: Backend, feature

#316 Implemented filtering, sorting and pagination for offers
  controllers/offer.js
  docs/offer/offer-schema.yaml
  docs/offer/offer.yaml
  models/offer.js
  models/review.js
  services/offer.js
  utils/offers/offerAggregateOptions.js
Labels: enhancement, Backend, feature, Prio

#298 Implemented update profile endpoint
  controllers/user.js
  docs/user/user-schema.yaml
  docs/user/user.yaml
  routes/user.js
  services/user.js
  test/integration/controllers/user.spec.js
  validation/services/user.js
Labels: enhancement, Backend, Prio

#323 Modified error handler
  consts/errors.js
  middlewares/error.js
  utils/getUniqueFields.js
Labels: Backend

#320 modified entity validation middleware, error msg, refactored code
  consts/errors.js
  controllers/category.js
  controllers/cooperation.js
  controllers/offer.js
  controllers/review.js
  controllers/subject.js
  docs/user/user-schema.yaml
  middlewares/entityValidation.js
  middlewares/setCurrentUserIdAndRole.js
  routes/adminInvitation.js
  routes/auth.js
  routes/category.js
  routes/cooperation.js
  routes/email.js
  routes/index.js
  routes/location.js
  routes/offer.js
  routes/review.js
  routes/subject.js
  routes/user.js
  services/adminInvitation.js
  services/category.js
  services/cooperation.js
  services/location.js
  services/offer.js
  services/review.js
  services/subject.js
  services/token.js
  services/user.js
  test/integration/controllers/category.spec.js
  test/integration/controllers/offer.spec.js
  test/integration/controllers/review.spec.js
  test/integration/controllers/subject.spec.js
  test/integration/controllers/user.spec.js
  utils/offers/offerAggregateOptions.js
Labels: enhancement, Backend

#326 Refactored test of users endpoints
  controllers/user.js
  services/user.js
  test/integration/controllers/user.spec.js
  utils/testUserAuth.js
Labels: Backend, tests

#328 Refactored offer
  docs/offer/offer-schema.yaml
  docs/offer/offer.yaml
  models/offer.js
  test/integration/controllers/offer.spec.js
  utils/offers/offerAggregateOptions.js
Labels: Backend

#325 Rewrote review update
  docs/review/review-schema.yaml
  docs/review/review.yaml
  services/review.js
  validation/services/review.js
Labels: Backend
