Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2023-09, with the labels that each got.

#549 (SP:0.5) Modify sorting in myResources
  services/attachment.js
  services/lesson.js
  services/quiz.js
Labels: Backend, feature

#555 added professional summary field
  services/chat.js
Labels: Backend

#553 Added creating chat on the first message
  consts/errors.js
  routes/message.js
  services/message.js
  utils/errorsHelper.js
Labels: Backend, feature

#566 Added content to lesson, fix swagger
  docs/finishedQuiz/finishedQuiz.yaml
  docs/lesson/lesson-schema.yaml
  docs/lesson/lesson.yaml
  models/lesson.js
  services/lesson.js
  test/integration/controllers/lesson.spec.js
Labels: Backend, feature

#552 Added population for attachments in getLessonById
  docs/lesson/lesson.yaml
  services/lesson.js
Labels: Backend, feature

#550 Update quiz endpoint
  controllers/quiz.js
  docs/quiz/quiz.yaml
  routes/quiz.js
  services/quiz.js
  test/integration/controllers/quiz.spec.js
Labels: Backend, feature

#574 Fixed updating blob name of attachment when validation failed
  services/attachment.js
Labels: bug, Backend

#572 Implemented "Get questions" endpoint with tests and docs
  controllers/question.js
  docs/questions/question.schema.yaml
  docs/questions/question.yaml
  routes/index.js
  routes/question.js
  services/question.js
  test/integration/controllers/question.spec.js
Labels: Backend, feature

#569 Added create questions enpoint
  consts/validation.js
  controllers/question.js
  docs/questions/questions.yaml
  models/question.js
  routes/question.js
  services/question.js
  test/integration/controllers/question.spec.js
Labels: Backend, feature

#575 Resources category model created
  consts/models.js
  docs/resourcesCategory/resourcesCategory.schema.yaml
  models/resourcesCategory.js
Labels: Backend

#588 changed chat body in swagger
  docs/chat/chat.yaml
Labels: Backend

#587 Implemented getAll tutor resources categories route
  controllers/resourcesCategory.js
  docs/resourcesCategory/resourcesCategory.yaml
  routes/index.js
  routes/resourcesCategory.js
  services/resourcesCategory.js
Labels: Backend, feature

#578 Added category field to lesson, attachment, quiz models
  docs/attachments/attachment.yaml
  docs/attachments/attachments-schema.yaml
  docs/lesson/lesson-schema.yaml
  docs/lesson/lesson.yaml
  docs/quiz/quiz-schema.yaml
  docs/quiz/quiz.yaml
  models/attachment.js
  models/lesson.js
  models/quiz.js
  services/lesson.js
  services/quiz.js
  test/integration/controllers/lesson.spec.js
  test/integration/controllers/quiz.spec.js
Labels: Backend

#593 added get resources category names and category to question
  controllers/question.js
  controllers/resourcesCategory.js
  docs/resourcesCategory/resourcesCategory.yaml
  models/question.js
  routes/resourcesCategory.js
  services/question.js
  services/resourcesCategory.js
Labels: Backend, feature

#585 Modify quiz model
  docs/quiz/quiz-schema.yaml
  models/quiz.js
Labels: Backend

#586 Added delete question endpoint
  controllers/question.js
  docs/questions/question.yaml
  routes/question.js
  services/question.js
Labels: Backend, feature

#598 fixed server crashing error and yaml warnings
  controllers/question.js
  docs/quiz/quiz-schema.yaml
  docs/quiz/quiz.yaml
  models/lesson.js
  models/offer.js
  models/user.js
  services/question.js
  test/integration/controllers/cooperation.spec.js
  test/integration/controllers/lesson.spec.js
Labels: bug, Backend

#601 Fixed question creation
  services/question.js
Labels: bug, Backend
