Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2023-11, with the labels that each got.

#617 modificate update question endpoint
  controllers/question.js
  docs/questions/question.yaml
  services/question.js
  test/integration/controllers/question.spec.js
Labels: Backend

#623 Implemented clear chat history endpoint
  controllers/message.js
  docs/chat/chat.yaml
  models/message.js
  routes/message.js
  services/message.js
  test/integration/controllers/message.spec.js
Labels: Backend, feature

#627 Adding util for categorization
  controllers/attachment.js
  controllers/lesson.js
  controllers/question.js
  controllers/quiz.js
  utils/getCategoriesOption.js
Labels: feature

#628 Add field for enrolledUsers in Offer
  docs/offer/offer-schema.yaml
  docs/offer/offer.yaml
  models/offer.js
  services/offer.js
  test/integration/controllers/offer.spec.js
Labels: Backend, feature

#637 Fixed wrong deletion logic from the DB
  services/message.js
Labels: bug, Backend

#631 Added accessToken to httpOnly cookies and changed tests with swagger settings
  consts/auth.js
  controllers/auth.js
  docs/adminInvitation/admin-invitation.yaml
  docs/attachments/attachment.yaml
  docs/auth/auth.yaml
  docs/category/category.yaml
  docs/chat/chat.yaml
  docs/comment/comment.yaml
  docs/cooperation/cooperation.yaml
  docs/course/course.yaml
  docs/finishedQuiz/finishedQuiz.yaml
  docs/lesson/lesson.yaml
  docs/message/message.yaml
  docs/notications/notification.yaml
  docs/offer/offer.yaml
  docs/questions/question.yaml
  docs/quiz/quiz.yaml
  docs/resourcesCategory/resourcesCategory.yaml
  docs/review/review.yaml
  docs/subject/subject.yaml
  docs/user/user.yaml
  middlewares/auth.js
  swagger-settings.js
  test/integration/controllers/attachments.spec.js
  test/integration/controllers/auth.spec.js
  test/integration/controllers/category.spec.js
  test/integration/controllers/chat.spec.js
  test/integration/controllers/comment.spec.js
  test/integration/controllers/cooperation.spec.js
  test/integration/controllers/course.spec.js
  test/integration/controllers/finishedQuiz.spec.js
  test/integration/controllers/lesson.spec.js
  test/integration/controllers/message.spec.js
  test/integration/controllers/notification.spec.js
  test/integration/controllers/offer.spec.js
  test/integration/controllers/question.spec.js
  test/integration/controllers/quiz.spec.js
  test/integration/controllers/resourcesCategory.spec.js
  test/integration/controllers/review.spec.js
  test/integration/controllers/subject.spec.js
  test/integration/controllers/user.spec.js
  test/unit/middlewares/auth.spec.js
Labels: Backend, feature

#633 Added fields to getQuizById
  services/quiz.js
Labels: Backend, feature

#642 Added get question by id service
  controllers/question.js
  routes/question.js
  services/question.js
Labels: Backend

#655 Updated edit attachment service
  services/attachment.js
Labels: Backend

#653 Added new method fields for get courses
  services/course.js
Labels: Backend

#641 Fixed request error
  cron-jobs/checkForLastLogin.js
Labels: bug, Backend, error
