Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2023-01, with the labels that each got.

#167 added subject model, route and swagger
  consts/errors.js
  consts/validation.js
  controllers/subject.js
  docs/category/category-schema.yaml
  docs/subject/subject-schema.yaml
  docs/subject/subject.yaml
  docs/tutor/tutor-schema.yaml
  models/subject.js
  models/tutor.js
  routes/index.js
  routes/subject.js
Labels: Backend, feature

#171 Changed auth services according to schemas
  consts/errors.js
  controllers/auth.js
  routes/auth.js
  services/auth.js
  services/student.js
  services/tutor.js
  test/integration/controllers/auth.spec.js
  utils/auth.js
  validation/schemas/login.js
Labels: Backend

#175 Feature/173/my profile endpoint
  middlewares/setCurrentUserId.js
  routes/student.js
  routes/tutor.js
Labels: enhancement, Backend, Auth, predecessor

#176 Subject implementation
  controllers/subject.js
  docs/subject/subject-schema.yaml
  docs/subject/subject.yaml
  models/subject.js
  routes/subject.js
  services/subject.js
  test/integration/controllers/subject.spec.js
Labels: Backend, feature
