Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2023-07, with the labels that each got.

#426 Added comments for cooperation
  consts/validation.js
  controllers/comment.js
  docs/comment/comment-schema.yaml
  docs/comment/comment.yaml
  middlewares/entityValidation.js
  models/comment.js
  models/cooperation.js
  models/notications.js
  routes/category.js
  routes/comment.js
  routes/cooperation.js
  routes/index.js
  routes/offer.js
  routes/review.js
  routes/subject.js
  routes/user.js
  services/comment.js
  test/integration/controllers/comment.spec.js
  test/integration/controllers/cooperation.spec.js
Labels: Backend, feature

#452 Created "Course" model and schema for documentation
  consts/models.js
  docs/course/course-schema.yaml
  models/cooperation.js
  models/course.js
  models/message.js
  models/offer.js
Labels: Backend, feature

#429 added title to allowedOfferFieldsForUpdate
  validation/services/offer.js
Labels: Backend

#469 Feature/create chat endpoint
  controllers/chat.js
  docs/chat/chat.yaml
  models/chat.js
  routes/chat.js
  routes/index.js
  services/chat.js
  test/integration/controllers/chat.spec.js
Labels: Backend, feature

#464 Feature/create message endpoint
  controllers/message.js
  docs/message/message.yaml
  routes/index.js
  routes/message.js
  services/message.js
  test/integration/controllers/message.spec.js
Labels: Backend, feature

#470 implemented getting notifications
  controllers/notification.js
  docs/notications/notification-shema.yaml
  docs/notications/notification.yaml
  models/notification.js
  routes/index.js
  routes/notification.js
  routes/user.js
  services/notification.js
  test/integration/controllers/notification.spec.js
Labels: Backend, feature

#468 Implemented update a course
  controllers/course.js
  docs/course/course.yaml
  routes/course.js
  routes/index.js
  services/course.js
  test/integration/controllers/course.spec.js
Labels: Backend, feature

#477 Feature/delete lesson endpoint
  controllers/lesson.js
  docs/lesson/lesson.yaml
  routes/lesson.js
  services/lesson.js
  test/integration/controllers/lesson.spec.js
Labels: Backend, feature

#471 Fix comment test
  services/chat.js
  test/integration/controllers/comment.spec.js
Labels: Backend

#476 add clear notifications endpoint
  controllers/notification.js
  docs/notications/notification.yaml
  routes/notification.js
  services/notification.js
  test/integration/controllers/course.spec.js
  test/integration/controllers/notification.spec.js
Labels: Backend, feature

#475 Implemented getCourses endpoint
  controllers/course.js
  docs/course/course.yaml
  routes/course.js
  services/course.js
  test/integration/controllers/course.spec.js
Labels: Backend, feature

#473 Implemented "Get lessons" endpoint
  controllers/lesson.js
  docs/lesson/lesson.yaml
  routes/lesson.js
  services/lesson.js
  test/integration/controllers/lesson.spec.js
Labels: Backend, feature

#485 implemented delete notification by ID
  controllers/notification.js
  docs/notications/notification.yaml
  routes/notification.js
  services/notification.js
  test/integration/controllers/notification.spec.js
Labels: Backend, feature

#484 implemented get messages endpoint
  controllers/message.js
  docs/chat/chat.yaml
  docs/message/message.yaml
  routes/chat.js
  routes/message.js
  services/message.js
  test/integration/controllers/message.spec.js
Labels: Backend, feature

#482 Created get one course endpoint
  controllers/course.js
  docs/course/course.yaml
  package-lock.json
  routes/course.js
  services/course.js
  test/integration/controllers/course.spec.js
Labels: Backend, feature

#483 Feature/463/get all users chats
  controllers/chat.js
  docs/chat/chat.yaml
  models/chat.js
  models/message.js
  routes/chat.js
  routes/user.js
  services/chat.js
  services/message.js
Labels: enhancement, Backend

#499 Implemented schema for attachments
  consts/models.js
  docs/attachments/attachments-schema.yaml
  models/attachments.js
Labels: Backend, feature
