Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2023-06, with the labels that each got.

#390 Fix user test
  controllers/user.js
  test/integration/controllers/user.spec.js
Labels: Backend, tests

#395 Changed aggregation for cooperation
  controllers/cooperation.js
  models/cooperation.js
  services/cooperation.js
  utils/cooperations/coopsAggregateOptions.js
Labels: Backend, feature

#396 Implemented upload service for images to azure
  configs/config.js
  consts/upload.js
  package-lock.json
  package.json
  services/upload.js
  services/user.js
  test/unit/services/upload.spec.js
Labels: Backend, feature

#397 Fixed offer`s filter
  controllers/offer.js
  models/offer.js
  services/offer.js
  utils/offers/offerAggregateOptions.js
Labels: Backend

#394 Fix auth tests
  test/integration/controllers/auth.spec.js
Labels: Backend, tests

#404 Fixed FAQ
  services/offer.js
Labels: bug, Backend

#402 Fixed bags in offer endpoints
  services/offer.js
  test/integration/controllers/offer.spec.js
  utils/offers/offerAggregateOptions.js
Labels: bug, Backend

#401 (SP: 0.5) Add count to get categories and subjects #392
  services/category.js
  services/subject.js
  test/integration/controllers/category.spec.js
  test/integration/controllers/offer.spec.js
  test/integration/controllers/review.spec.js
  test/integration/controllers/subject.spec.js
Labels: good first issue, Backend, feature

#409 Fixed aggregations for offer and coop
  models/category.js
  services/offer.js
  utils/cooperations/coopsAggregateOptions.js
  utils/offers/offerAggregateOptions.js
Labels: bug, Backend

#416 changed categories, subject response and fix tests
  services/category.js
  services/subject.js
  test/integration/controllers/category.spec.js
  test/integration/controllers/offer.spec.js
  test/integration/controllers/review.spec.js
  test/integration/controllers/subject.spec.js
Labels: Backend

#413 fix/user-service
  services/user.js
Labels: bug, Backend

#414 Implemented cooperation tests
  routes/cooperation.js
  test/integration/controllers/cooperation.spec.js
Labels: Backend, tests

#411 Should show categories with subjects
  consts/categories.js
  controllers/category.js
  services/category.js
  test/integration/controllers/category.spec.js
  test/integration/controllers/offer.spec.js
  test/integration/controllers/review.spec.js
  test/integration/controllers/subject.spec.js
  utils/categories/categoriesAggregateOptions.js
  utils/categories/categoryNamesAggregateOptions.js
Labels: Backend, feature

#418 Added roles for initiator and receiver of coop
  controllers/cooperation.js
  docs/cooperation/cooperation.schema.yaml
  docs/cooperation/cooperation.yaml
  models/cooperation.js
  services/cooperation.js
  utils/cooperations/coopsAggregateOptions.js
Labels: Backend, feature

#410 Fixed sort in offers
  utils/offers/offerAggregateOptions.js
Labels: bug, Backend

#423 Added need acction, populated price from offer
  consts/validation.js
  controllers/cooperation.js
  models/cooperation.js
  services/cooperation.js
  utils/cooperations/coopsAggregateOptions.js
Labels: Backend

#420 Changed offer's status
  consts/validation.js
  models/offer.js
  test/integration/controllers/offer.spec.js
  utils/offers/offerAggregateOptions.js
Labels: Backend

#424 Fixed test of users
  services/user.js
Labels: bug, Backend

#454 Feature/notification_model
  consts/models.js
  consts/validation.js
  docs/notications/notifications-shema.yaml
  models/notications.js
Labels: Backend, feature

#458 Added status field for creating offer
  services/offer.js
  validation/services/offer.js
Labels: Backend, feature

#456 Added message model
  consts/models.js
  docs/message/message-schema.yaml
  models/message.js
Labels: Backend, feature

#430 Modified docs and tests for cooperations
  docs/cooperation/cooperation.schema.yaml
  docs/cooperation/cooperation.yaml
  test/integration/controllers/cooperation.spec.js
Labels: Backend

#455 Added preventing reviews, offers and coops from being updated by non-invlolved users
  controllers/cooperation.js
  controllers/offer.js
  controllers/review.js
  services/cooperation.js
  services/offer.js
  services/review.js
Labels: Backend, feature

#451 Added lesson model and docs for lesson body
  consts/models.js
  consts/validation.js
  docs/lesson/lesson-schema.yaml
  models/cooperation.js
  models/lesson.js
  models/notications.js
  models/offer.js
  routes/category.js
Labels: Backend, feature
