Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2023-02, with the labels that each got.

#196 refactor user model, docs
  consts/errors.js
  consts/validation.js
  docs/user/user-schema.yaml
  docs/user/user.yaml
  initialization/serverSetup.js
  middlewares/appLanguage.js
  models/student.js
  models/tutor.js
  models/user.js
  routes/auth.js
  routes/email.js
  services/user.js
  test/unit/middlewares/language.spec.js
Labels: documentation, Backend, Auth, predecessor

#192 implemented api for countries and cities
  controllers/location.js
  routes/index.js
  routes/location.js
  services/location.js
Labels: Backend, feature

#194 feature/192/refactor-subject
  consts/errors.js
  controllers/subject.js
  docs/subject/subject-schema.yaml
  docs/subject/subject.yaml
  models/subject.js
  routes/subject.js
  services/subject.js
  test/integration/controllers/subject.spec.js
Labels: Backend, feature

#195 Refactored review model and swagger
  docs/review/review-schema.yaml
  docs/review/review.yaml
  models/review.js
Labels: documentation, Backend

#200 Refactored auth, removed tutor and student models
  controllers/student.js
  controllers/tutor.js
  docs/student/student-schema.yaml
  docs/student/student.yaml
  docs/tutor/tutor-schema.yaml
  docs/tutor/tutor.yaml
  models/student.js
  models/tutor.js
  routes/index.js
  routes/student.js
  routes/tutor.js
  services/auth.js
  services/student.js
  services/tutor.js
  services/user.js
  utils/auth.js
Labels: Backend, feature

#201 added tests for user, changed routes/model/swagger
  controllers/user.js
  docs/user/user-schema.yaml
  docs/user/user.yaml
  routes/user.js
  services/user.js
  test/integration/controllers/user.spec.js
  test/unit/middlewares/auth.spec.js
Labels: Backend, feature

#170 Implemented controller, service and tests for review
  controllers/review.js
  routes/review.js
  services/review.js
  test/integration/controllers/review.spec.js
  utils/testUserAuth.js
Labels: Backend, feature

#206 130/Implemented unit test for checkForLastLogin
  cron-jobs/checkForLastLogin.js
  cron-jobs/scheduledCronJobs.js
  test/unit/cron-jobs/checkForLastLogin.spec.js
  test/unit/cron-jobs/scheduledCronJobs.spec.js
Labels: Backend, tests, feature

#212 Sonar-project.properties file updated
  sonar-project.properties
Labels: enhancement, Backend

#211 Removed Role model
  models/role.js
Labels: Backend

#214 Feature/166/one review only
  consts/errors.js
  models/review.js
Labels: good first issue, Backend, feature
