Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2024-10, with the labels that each got.

#934 API endpoint for getting courses and cooperations by the resource ID
  docs/coursesCooperations/coursesCooperations-schema.yaml
  docs/coursesCooperations/coursesCooperations.yaml
  src/controllers/coursesCooperations.js
  src/routes/coursesCooperations.js
  src/routes/index.js
  src/services/coursesCooperations.js
  src/test/integration/controllers/coursesCooperations.spec.js
  src/test/test-utils.js
Labels: Backend, feature

#877 Update dotenv
  package.json
Labels: Backend, dependency

#867 Update eslint and eslint-config-prettier
  .eslintrc.json
  eslint.config.mjs
  jest.config.cjs
  package.json
  sonar-project.properties
  src/routes/finishedQuiz.js
  src/services/token.js
  src/utils/getSortOptions.js
Labels: Backend, dependency

#925 Add admin role check in user creation
  src/services/user.js
  src/test/integration/controllers/user.spec.js
Labels: enhancement, Backend, Auth

#937 Implemented possibility of adding duplicated resources
  src/services/lesson.js
  src/services/quiz.js
Labels: Backend, feature

#939 Fixed bug when the user is marked as offline even if they have at least one session open
  src/event-handlers/activityHandler.js
  src/test/unit/event-handlers/activityHandler.spec.js
Labels: bug, Backend, sockets

#880 Updated database dependencies
  package.json
  src/services/attachment.js
  src/services/chat.js
  src/services/course.js
  src/services/lesson.js
  src/services/message.js
  src/services/note.js
  src/services/offer.js
  src/services/question.js
  src/services/quiz.js
  src/services/resourcesCategory.js
  src/services/review.js
  src/services/subject.js
  src/services/user.js
  src/test/integration/controllers/cooperation.spec.js
  src/test/integration/controllers/finishedQuiz.spec.js
  src/test/integration/controllers/note.spec.js
  src/test/integration/controllers/offer.spec.js
  src/test/integration/controllers/user.spec.js
  src/utils/categories/conditionCreator.js
  src/utils/cooperations/coopsAggregateOptions.js
  src/utils/offers/offerAggregateOptions.js
  src/utils/reviews/reviewStatsAggregation.js
Labels: Backend, dependency
