Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2024-05, with the labels that each got.

#776 Added account deactivation and activation logic
  src/consts/validation.js
  src/controllers/user.js
  src/routes/user.js
  src/test/integration/controllers/offer.spec.js
  src/test/integration/controllers/user.spec.js
  src/utils/offers/offerAggregateOptions.js
Labels: feature

#783 updated user model, serivice to update profeccional logic
  src/models/user.js
  src/services/user.js
  src/utils/users/photoCheck.js
  src/validation/services/user.js
Labels: Backend, feature

#778 Fixed cooperation for saving and view
  src/consts/models.js
  src/middlewares/coopSectionsValidation.js
  src/models/cooperation.js
  src/test/integration/controllers/cooperation.spec.js
  src/test/unit/middlewares/coopSectionsValidation.spec.js
  src/test/unit/utils/validateAttachment.spec.js
  src/test/unit/utils/validateQuiz.spec.js
  src/utils/cooperations/sections/validateAttachment.js
  src/utils/cooperations/sections/validateCommonFields.js
  src/utils/cooperations/sections/validateLesson.js
  src/utils/cooperations/sections/validateQuiz.js
Labels: Backend

#781 Implement availability object
  src/models/attachment.js
  src/models/lesson.js
  src/models/quiz.js
  src/test/integration/controllers/attachments.spec.js
  src/test/integration/controllers/lesson.spec.js
  src/test/integration/controllers/quiz.spec.js
Labels: Backend, feature

#785 Feature/782/main subjects
  docs/user/user-schema.yaml
  docs/user/user.yaml
  src/controllers/user.js
  src/models/helpers/user-main-subjects.js
  src/models/user.js
  src/services/user.js
  src/test/integration/controllers/user.spec.js
  src/test/unit/services/user.spec.js
  src/test/unit/utils/parseBoolean.spec.js
  src/utils/parseBoolean.js
Labels: Backend, feature
