Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2024-06, with the labels that each got.

#786 Change password endpoint/#784
  docs/auth/auth.yaml
  src/consts/errors.js
  src/controllers/auth.js
  src/routes/auth.js
  src/services/auth.js
  src/test/integration/controllers/auth.spec.js
  src/validation/schemas/changePassword.js
Labels: Backend, feature

#791 Added stepper support
  src/services/user.js
  src/test/unit/services/user.spec.js
Labels: bug, Backend, priority: high

#800 Fixed deletion bug
  src/services/user.js
  src/test/unit/services/user.spec.js
Labels: bug, Backend
