Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2024-07, with the labels that each got.

#794 Implemented sorting categories by totaloffers
  docs/category/category.yaml
  src/test/integration/controllers/categoriesAggregateOptions.spec.js
  src/utils/categories/categoriesAggregateOptions.js
Labels: Backend, feature

#799 Make GetSubjects endpoint return category appearance
  docs/subject/subject-schema.yaml
  docs/subject/subject.yaml
  src/services/subject.js
  src/test/integration/controllers/subject.spec.js
Labels: Backend, feature

#802 Fixed issue during registration in 'incognito' mode #801
  src/consts/validation.js
  src/emails/index.js
  src/emails/uk/confirm-email.pug
  src/emails/uk/index.pug
  src/emails/uk/invite-admin.pug
  src/emails/uk/long-time-without-login.pug
  src/emails/uk/reset-password.pug
  src/emails/uk/sucessful-password-reset.pug
  src/middlewares/appLanguage.js
  src/test/unit/middlewares/language.spec.js
Labels: bug, Backend

#804 Added 'Remember me' logic to adjust Refresh JWT token expiration and cookie maxAge #803
  .github/workflows/main.yaml
  src/configs/config.js
  src/consts/auth.js
  src/controllers/auth.js
  src/services/auth.js
  src/services/token.js
  src/test/integration/controllers/auth.spec.js
  src/test/unit/services/token.spec.js
Labels: Backend, Auth, feature

#814 Removed redundant skip and limit options to resolve conflicts
  src/utils/categories/categoriesAggregateOptions.js
Labels: bug, Backend

#796 Refactored swagger docs to match actual category schema
  docs/category/category.yaml
  docs/course/course.yaml
  docs/review/review.yaml
  src/consts/categories.js
  src/services/category.js
Labels: bug, documentation, Backend

#807 Make getUserById endpoint return mainSubjects category appearance
  docs/user/user-schema.yaml
  docs/user/user.yaml
  src/services/user.js
Labels: enhancement, Backend

#816 Fixed failing tests on GitHub Actions (CI/Test_DEV) #812
  jest.config.js
  src/test/integration/controllers/auth.spec.js
  src/test/unit/services/token.spec.js
  src/validation/schemas/login.js
Labels: bug, Backend, Auth, email, error, priority: high

#810 Fixed sorting for fetched subjects
  src/services/subject.js
Labels: bug, Backend

#821 Resolved issue with Date availability field type in cooperation resource #820
  src/consts/validation.js
Labels: bug, Backend, error

#839 Uncommented stage
  azure-pipeline.yaml
Labels: Backend, devOps, priority: medium

#841 Expanded workflow triggers to include feature branches #840
  .github/workflows/main.yaml
Labels: Backend, devOps

#842 Refactored cooperation model #788
  src/middlewares/coopSectionsValidation.js
  src/models/cooperation.js
  src/test/integration/controllers/cooperation.spec.js
  src/test/unit/middlewares/coopSectionsValidation.spec.js
Labels: enhancement, Backend
