Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2024-01, with the labels that each got.

#681 refactored course and auth tests
  models/course.js
  test/integration/controllers/auth.spec.js
  test/integration/controllers/course.spec.js
Labels: Backend, tests

#691 fixed error with map is not a function and sorting
  controllers/lesson.js
  utils/cooperations/coopsAggregateOptions.js
  utils/getSortOptions.js
  utils/offers/offerAggregateOptions.js
  utils/users/createAggregateOptions.js
Labels: bug, Backend

#694 fixed quiz test by adding resource type field
  test/integration/controllers/category.spec.js
  test/integration/controllers/quiz.spec.js
Labels: bug, Backend

#688 Added order field for course section
  docs/course/course-schema.yaml
  docs/course/course.yaml
  models/course.js
Labels: Backend

#697 added settings to create quiz
  docs/quiz/quiz.yaml
  services/quiz.js
Labels: Backend, feature

#692 Fixed files uploading with non-ascii in the name
  controllers/attachment.js
  package.json
Labels: bug, enhancement, Backend

#711 Added filter to get notes
  services/note.js
Labels: Backend

#706 added category populate for getUserById
  docs/user/user-schema.yaml
  docs/user/user.yaml
  services/user.js
Labels: Backend

#709 added sections to cooperation schema and updated swagger with controller
  docs/cooperation/cooperation-schema.yaml
  docs/cooperation/cooperation.yaml
  models/cooperation.js
  services/cooperation.js
  utils/cooperations/coopsAggregateOptions.js
Labels: Backend, feature

#704 Added title to cooperation
  docs/cooperation/cooperation-schema.yaml
  docs/cooperation/cooperation.yaml
  models/cooperation.js
  services/cooperation.js
  test/integration/controllers/cooperation.spec.js
Labels: Backend, feature

#690 fixed courses for sorting
  controllers/course.js
  services/course.js
Labels: Backend, feature

#718 Fixed tests in note.spec.js and cooperation.spec.js
  test/integration/controllers/cooperation.spec.js
  test/integration/controllers/note.spec.js
Labels: Backend
