Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2024-08, with the labels that each got.

#853 Fixed missing resourceType in response on getting cooperation by ID #848
  src/test/unit/utils/validateQuestion.spec.js
  src/utils/cooperations/sections/validateAttachment.js
  src/utils/cooperations/sections/validateLesson.js
  src/utils/cooperations/sections/validateQuestion.js
  src/utils/cooperations/sections/validateQuiz.js
Labels: bug, Backend, error, Prio

#857 Added isDuplicate field to resource models and updated get queries
  docs/attachments/attachment.yaml
  docs/lesson/lesson.yaml
  docs/questions/question.yaml
  docs/quiz/quiz.yaml
  src/controllers/attachment.js
  src/controllers/lesson.js
  src/controllers/question.js
  src/controllers/quiz.js
  src/models/attachment.js
  src/models/lesson.js
  src/models/question.js
  src/models/quiz.js
Labels: enhancement, Backend, feature

#861 Added possibility to add resources to courses by creating a duplicate in resource collection
  src/services/course.js
  src/test/integration/controllers/course.spec.js
  src/utils/resourceModelMapping.js
Labels: enhancement, Backend, feature

#844 Added notificationSettings for the user in DB
  docs/user/user-schema.yaml
  docs/user/user.yaml
  src/models/user.js
  src/services/user.js
  src/validation/services/user.js
Labels: enhancement, Backend

#855 Added populate for initiator and receiver fields
  docs/cooperation/cooperation.yaml
  src/services/cooperation.js
  src/test/integration/controllers/cooperation.spec.js
  src/test/unit/cron-jobs/checkForLastLogin.spec.js
Labels: Backend, predecessor

#870 Updated cron
  package.json
Labels: Backend, dependency

#863 Update jest
  package.json
  src/test/integration/controllers/cooperation.spec.js
  src/test/integration/controllers/finishedQuiz.spec.js
  src/test/integration/controllers/note.spec.js
  src/test/integration/controllers/notification.spec.js
Labels: Backend, dependency

#878 Update googleapis
  package.json
Labels: Backend, dependency

#871 Update email-templates
  package.json
Labels: Backend, dependency

#869 Update swagger-jsdoc and swagger-ui-express
  package.json
Labels: Backend, dependency

#868 Update jsonwebtoken
  package.json
Labels: Backend, dependency

#864 Update husky
  .husky/pre-commit
  .husky/pre-push
  package.json
Labels: Backend, dependency

#866 Update prettier
  package.json
Labels: Backend, dependency

#875 Create endpoint for toggling bookmarks
  docs/user/user-schema.yaml
  docs/user/user.yaml
  src/controllers/user.js
  src/routes/user.js
  src/services/user.js
  src/test/integration/controllers/user.spec.js
Labels: Backend, feature

#891 Resolved BSONTypeError when adding duplicate resources to Course/Cooperation
  src/utils/handleResources.js
Labels: bug, Backend, Prio, priority: high

#886 Updated EditProfile so new categories are updated on backend.
  src/services/user.js
  src/test/unit/services/user.spec.js
Labels: enhancement, Backend

#845 Refactored course schema & general changes
  docs/attachments/attachment.yaml
  docs/cooperation/cooperation-schema.yaml
  docs/cooperation/cooperation.yaml
  docs/course/course-schema.yaml
  docs/course/course.yaml
  docs/lesson/lesson.yaml
  docs/questions/question.yaml
  docs/quiz/quiz.yaml
  src/consts/models.js
  src/consts/validation.js
  src/controllers/attachment.js
  src/controllers/lesson.js
  src/controllers/question.js
  src/controllers/quiz.js
  src/middlewares/coopSectionsValidation.js
  src/models/attachment.js
  src/models/cooperation.js
  src/models/course.js
  src/models/lesson.js
  src/models/question.js
  src/models/quiz.js
  src/routes/cooperation.js
  src/services/cooperation.js
  src/services/course.js
  src/test/integration/controllers/attachments.spec.js
  src/test/integration/controllers/cooperation.spec.js
  src/test/integration/controllers/course.spec.js
  src/test/integration/controllers/quiz.spec.js
  src/test/unit/middlewares/coopSectionsValidation.spec.js
  src/test/unit/utils/deleteNotAllowedFields.spec.js
  src/test/unit/utils/validateAttachment.spec.js
  src/test/unit/utils/validateCommonFields.spec.js
  src/test/unit/utils/validateLesson.spec.js
  src/test/unit/utils/validateQuestion.spec.js
  src/test/unit/utils/validateQuiz.spec.js
  src/utils/cooperations/sections/deleteNotAllowedFields.js
  src/utils/cooperations/sections/validateAttachment.js
  src/utils/cooperations/sections/validateCommonFields.js
  src/utils/cooperations/sections/validateLesson.js
  src/utils/cooperations/sections/validateQuestion.js
  src/utils/cooperations/sections/validateQuiz.js
  src/utils/handleResources.js
  src/utils/resourceModelMapping.js
  src/utils/resourceTypeMapping.js
Labels: enhancement, Backend, predecessor, feature, Prio

#884 Create an endpoint for getting bookmarked offers
  docs/user/user-schema.yaml
  docs/user/user.yaml
  src/controllers/user.js
  src/routes/user.js
  src/services/user.js
  src/test/integration/controllers/user.spec.js
Labels: Backend, feature

#883 Change getMessages in messageService
  docs/message/message-schema.yaml
  docs/message/message.yaml
  src/services/message.js
  src/test/integration/controllers/message.spec.js
Labels: Backend

#893 Delete course with duplicated resources
  src/services/course.js
  src/utils/deleteDuplicateResources.js
Labels: enhancement, Backend, feature
