Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2024-11, with the labels that each got.

#953 Fix swagger docs error POST /lessons
  docs/lesson/lesson.yaml
Labels: bug, documentation, good first issue, Backend

#955 Сhanged import order in course tests
  src/test/integration/controllers/course.spec.js
Labels: bug, Backend, tests

#963 Fix sonar issues in src/middlewares/entityValidation.js file
  src/middlewares/entityValidation.js
Labels: bug, Backend

#966 Add a status field for resources in cooperation model
  docs/cooperation/cooperation-schema.yaml
  docs/cooperation/cooperation.yaml
  docs/quiz/quiz-schema.yaml
  docs/user/user-schema.yaml
  src/consts/validation.js
  src/models/cooperation.js
Labels: enhancement, Backend

#989 Fix server error for invalid role parameter in /users/{id}
  docs/user/user.yaml
  src/consts/requestDataSource.js
  src/middlewares/validation.js
  src/routes/user.js
  src/utils/validationHelper.js
  src/validation/schemas/getUserById.js
Labels: bug, Backend

#1004 Added aboutStudent field & extended update logic
  src/models/user.js
  src/services/user.js
  src/validation/services/user.js
Labels: Backend, feature

#1014 Added ability to use special characters for First Name and Last Name
  src/consts/validation.js
Labels: Backend, priority: medium
