Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2024-12, with the labels that each got.

#947 Implement last time online for users
  docs/user/user-schema.yaml
  docs/user/user.yaml
  src/event-handlers/activityHandler.js
  src/models/user.js
  src/services/user.js
  src/test/unit/event-handlers/activityHandler.spec.js
  src/test/unit/services/user.spec.js
Labels: Backend, feature, sockets

#1011 Fix an ability to attach files on /attachments endpoint
  docs/attachments/attachment.yaml
Labels: bug, documentation, Backend

#1018 Fix status code in GET /users/{id} swagger example
  docs/user/user.yaml
Labels: bug, documentation, Backend

#1012 Fix swagger auth on /chat/{id}/messages endpoint
  docs/chat/chat.yaml
Labels: bug, documentation, Backend

#995 Fix swagger duplication on GET /user/{id} endpoint
  docs/user/user.yaml
Labels: bug, documentation, Backend

#1005 Add Resource Completion Status Update Endpoint for Cooperations
  docs/cooperation/cooperation-schema.yaml
  docs/cooperation/cooperation.yaml
  src/consts/errors.js
  src/controllers/cooperation.js
  src/routes/cooperation.js
  src/services/cooperation.js
  src/test/integration/controllers/cooperation.spec.js
  src/validation/schemas/cooperation.js
Labels: documentation, enhancement, Backend

#1002 Added ownership middleware
  sonar-project.properties
  src/consts/auth.js
  src/consts/modelPath.js
  src/middlewares/asyncWrapper.js
  src/middlewares/auth.js
  src/routes/attachment.js
  src/routes/cooperation.js
  src/routes/course.js
  src/routes/lesson.js
  src/routes/question.js
  src/routes/quiz.js
  src/services/user.js
  src/test/unit/services/user.spec.js
Labels: Backend, Auth

#1024 Fix incorrect swagger section tags in Categories and Offers endpoints
  docs/category/category.yaml
Labels: bug, documentation, Backend

#1025 Migrated from azure-storage to azure/storage-blob
  package-lock.json
  package.json
  src/services/upload.js
  src/test/integration/controllers/attachments.spec.js
  src/test/unit/services/upload.spec.js
Labels: enhancement, Backend, dependency

#1021 Refactor reviews endpoints for correct data flow
  docs/review/review-schema.yaml
  docs/review/review.yaml
  docs/user/user.yaml
  src/consts/errors.js
  src/controllers/review.js
  src/middlewares/idValidation.js
  src/routes/review.js
  src/routes/user.js
  src/services/cooperation.js
  src/services/review.js
  src/test/integration/controllers/review.spec.js
  src/utils/checkIdValidity.js
  src/utils/reviews/getReviewsAggregateOptions.js
  src/utils/reviews/reviewStatsAggregation.js
  src/utils/validationHelper.js
  src/validation/schemas/review.js
Labels: Backend

#1027 SP(0.5): Add 409 response in Swagger docs for user patch
  docs/user/user.yaml
Labels: bug, Backend

#1026 Add logic to initiate the cooperation closing process
  src/consts/validation.js
  src/services/cooperation.js
  src/test/integration/controllers/cooperation.spec.js
Labels: enhancement, Backend, priority: high

#1038 Fix unique constraint on reviews by author and targetUserId
  jest.config.js
  migrate-mongo-config.js
  migrations/20241203085442-remove-unique-author-target-user-index.js
  package-lock.json
  package.json
  sonar-project.properties
  src/models/review.js
  src/test/migrations/20241203085442-remove-unique-author-target-user-index.spec.js
Labels: Backend

#1063 Fixed swagger description for getting chat messages
  docs/chat/chat.yaml
Labels: bug, documentation, Backend

#1023 Hide closed resources from student
  docs/cooperation/cooperation-schema.yaml
  docs/cooperation/cooperation.yaml
  src/consts/user.js
  src/controllers/cooperation.js
  src/services/cooperation.js
  src/test/integration/controllers/cooperation.spec.js
  src/utils/cooperations/getCooperationByIdQueryPipeline.js
Labels: enhancement, Backend

#1065 The endpoint GET /categories/{id}/subjects doesn't correspond to the actual endpoint GET /categories/subjects/names
  docs/category/category-schema.yaml
  docs/category/category.yaml
Labels: bug, Backend

#1070 Safe Test Runner for Mongoose Models
  jest.config.js
  package.json
  src/configs/config.js
  src/consts/errors.js
  src/test/helpers.js
  src/test/setup.js
  src/test/setupSafeTest.js
  src/test/test-consts.js
  src/utils/isRestrictedPath.js
Labels: Backend, tests

#1095 Fixed incorrect field assignment in Offers
  docs/category/category-schema.yaml
  docs/offer/offer-schema.yaml
  docs/offer/offer.yaml
  docs/subject/subject-schema.yaml
  docs/user/user-schema.yaml
Labels: bug, documentation, Backend

#1076 Add cron job for opening scheduled cooperation resources
  src/cron-jobs/openScheduledCooperationResources.js
  src/cron-jobs/scheduledCronJobs.js
  src/services/cooperation.js
  src/test/unit/cron-jobs/openScheduledCooperationResources.spec.js
  src/test/unit/cron-jobs/scheduledCronJobs.spec.js
Labels: enhancement, Backend

#1068 Add missed fields in chat schema & update examples in Swagger docs
  docs/chat/chat-schema.yaml
  docs/chat/chat.yaml
Labels: documentation, Backend
