Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2024-09, with the labels that each got.

#895 Fixed swagger docs for the GET bookmarked offers endpoint
  docs/user/user.yaml
Labels: bug, Backend

#902 Fixed sonar error
  src/controllers/cooperation.js
  src/test/integration/controllers/cooperation.spec.js
  src/test/unit/utils/cooperations/coopsAggregateOptions.spec.js
  src/utils/cooperations/coopsAggregateOptions.js
Labels: Backend

#904 Removed the "availability" field from the Lesson, Quiz, Attachment entities #903
  docs/cooperation/cooperation-schema.yaml
  docs/cooperation/cooperation.yaml
  src/models/attachment.js
  src/models/cooperation.js
  src/models/lesson.js
  src/models/quiz.js
  src/test/integration/controllers/attachments.spec.js
  src/test/integration/controllers/cooperation.spec.js
  src/test/integration/controllers/course.spec.js
  src/test/integration/controllers/lesson.spec.js
  src/test/integration/controllers/quiz.spec.js
Labels: enhancement, Backend, refuck, priority: high

#906 Email verify message enhancement
  src/emails/css/index.css
  src/emails/en/confirm-email.pug
  src/emails/uk/confirm-email.pug
Labels: enhancement

#924 Setup socket server and implemented user activity handlers
  package.json
  src/event-handlers/activityHandler.js
  src/initialization/serverSetup.js
  src/initialization/socketServerSetup.js
  src/middlewares/auth.js
  src/test/unit/event-handlers/activityHandler.spec.js
  src/test/unit/middlewares/authSocket.spec.js
Labels: Backend, feature, sockets

#928 Implemented sending token via cookie for auth in the socket server
  package.json
  src/initialization/socketServerSetup.js
  src/middlewares/auth.js
  src/test/unit/middlewares/authSocket.spec.js
Labels: Backend, feature, sockets

#929 Fix swagger docs error GET /notifications
  docs/notications/notification-shema.yaml
Labels: bug, documentation, Backend

#930 Fix swagger docs error GET /lessons
  docs/lesson/lesson-schema.yaml
  docs/lesson/lesson.yaml
Labels: bug, documentation, Backend

#932 Implemented message handlers for the chat page
  src/event-handlers/messageHandler.js
  src/initialization/socketServerSetup.js
  src/services/message.js
  src/test/unit/event-handlers/messageHandler.spec.js
Labels: Backend, feature, sockets

#933 Fix swagger docs error POST /quizzes
  docs/quiz/quiz-schema.yaml
Labels: bug, documentation, Backend

#922 Fixed swagger docs for Resources Categories endpoints
  docs/resourcesCategory/resourcesCategory.schema.yaml
  docs/resourcesCategory/resourcesCategory.yaml
Labels: bug, documentation, Backend

#921 Fixed swagger docs for questions endpoints
  docs/questions/question.schema.yaml
Labels: bug, documentation, Backend

#920 Fixed swagger docs for PATCH /auth/change-password/{id}
  docs/auth/auth-schema.yaml
Labels: bug, documentation, Backend

#899 ( SP: 1) Improved security for bookmarks endpoints
  src/controllers/user.js
  src/test/integration/controllers/user.spec.js
  src/test/unit/utils/tokenValidation.spec.js
  src/utils/testUserAuth.js
  src/utils/users/tokenValidation.js
Labels: enhancement, Backend
