Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2024-02, with the labels that each got.

#724 added coverage for ResourseCategory and Upload tests
  test/integration/controllers/resourcesCategory.spec.js
  test/unit/services/upload.spec.js
Labels: Backend, tests

#723 added coverage for finishedQuiz and location services
  controllers/finishedQuiz.js
  routes/location.js
  test/integration/controllers/finishedQuiz.spec.js
  test/integration/controllers/location.spec.js
Labels: Backend, tests

#725 Increased coverage of Question and Cooperation tests
  controllers/question.js
  test/integration/controllers/cooperation.spec.js
  test/integration/controllers/question.spec.js
Labels: Backend, tests

#728 (SP: 1) Improve coverage of Auth tests
  test/integration/controllers/auth.spec.js
Labels: Backend, tests

#729 Improved review and create aggregate coverage
  test/integration/controllers/review.spec.js
  test/integration/controllers/user.spec.js
Labels: Backend, tests

#743 added coverage for category and notes tests
  services/note.js
  test/integration/controllers/category.spec.js
  test/integration/controllers/note.spec.js
Labels: Backend, tests

#741 Improved coverage of course and offer services
  services/course.js
  services/offer.js
  test/integration/controllers/course.spec.js
  test/integration/controllers/offer.spec.js
Labels: Backend, tests

#744 added coverage to CoopsAggregateOptions and OfferAggregateOptions tests
  test/integration/controllers/cooperation.spec.js
  test/integration/controllers/offerAggregateOptions.spec.js
  utils/offers/offerAggregateOptions.js
Labels: Backend, tests

#740 Added tests for attachments and quiz
  test/integration/controllers/attachments.spec.js
  test/integration/controllers/quiz.spec.js
Labels: Backend, tests

#730 implemented cooperation sections activity validation
  consts/errors.js
  consts/validation.js
  controllers/attachment.js
  middlewares/coopSectionsValidation.js
  routes/cooperation.js
  services/cooperation.js
  test/unit/middlewares/coopSectionsValidation.spec.js
  test/unit/utils/deleteNotAllowedFields.spec.js
  test/unit/utils/validateAttachment.spec.js
  test/unit/utils/validateCommonFields.spec.js
  test/unit/utils/validateLesson.spec.js
  test/unit/utils/validateQuestion.spec.js
  test/unit/utils/validateQuiz.spec.js
  utils/cooperations/sections/deleteNotAllowedFields.js
  utils/cooperations/sections/validateAttachment.js
  utils/cooperations/sections/validateCommonFields.js
  utils/cooperations/sections/validateLesson.js
  utils/cooperations/sections/validateQuestion.js
  utils/cooperations/sections/validateQuiz.js
Labels: Backend, feature

#748 added null as a default value for user nativeLanguage field
  models/user.js
Labels: bug, Backend

#745 Improved review and message service coverage
  services/message.js
  services/review.js
  test/integration/controllers/message.spec.js
  test/integration/controllers/review.spec.js
Labels: Backend, tests

#751 refactored sorting for course
  controllers/course.js
  services/course.js
Labels: bug, Backend

#753 Prevent creating a new chat if it`s already exists with same members
  consts/errors.js
  services/chat.js
  test/integration/controllers/chat.spec.js
  test/integration/controllers/message.spec.js
Labels: bug, Backend

#754 Fix Sonar issues for getUniqueFields and testUserAuth
  utils/getUniqueFields.js
  utils/testUserAuth.js
Labels: bug, Backend

#755 Fixed multer security issue
  middlewares/multer.js
Labels: bug, Backend
