Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2024-04, with the labels that each got.

#767 Feature/766/add youtube link
  docs/user/user-schema.yaml
  docs/user/user.yaml
  src/models/user.js
  src/services/user.js
  src/validation/services/user.js
Labels: Backend

#769 Fix deletion of the current user profile photo when updating user data
  .husky/pre-commit
  src/services/user.js
  src/test/integration/controllers/user.spec.js
Labels: bug, Backend

#771 added attachment response to PATCH request
  src/controllers/attachment.js
  src/services/attachment.js
Labels: enhancement, Backend

#773 Implemented getting courses with filters
  src/controllers/course.js
Labels: enhancement, Backend

#775 Enable students to access lessons
  src/routes/lesson.js
  src/test/integration/controllers/lesson.spec.js
Labels: bug, Backend
