Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2025-05, with the labels that each got.

#1346 chore(dependabot): delete
  .github/dependabot.yml
Labels: DevOps

#1344 Wrote safe tests for chat model #1040
  src/test/integration/models/chat.spec.js
  src/test/unit/services/user.spec.js
Labels: Backend, tests

#1165 Added safe tests for category model
  src/test/integration/models/category.spec.js
Labels: Backend, tests

#1333 Upgrade packages because of Vulnerabilities in Dependencies (inflight, fast-xml-parser)
  package-lock.json
Labels: Backend, priority: high, dependency, Security

#1351 Enhanced validation for country and city fields
  package-lock.json
  package.json
  src/utils/validation/fieldValidators.js
  src/utils/validation/schemaValidators.js
  src/validation/schemas/users/updateUserValidationSchema.js
Labels: bug, Backend

#1350 Missing down Method in Migration delete-old-fields-in-cooperatives-and-add-new-ones #1136
  migrations/20241220213859-delete-old-fields-in-cooperatives-and-add-new-ones.js
  package-lock.json
  src/test/migrations/20241220213859-delete-old-fields-in-cooperatives-and-add-new-ones.spec.js
Labels: bug, Backend

#1354 Add removeConfirmToken after confirmEmail
  src/services/auth.js
  src/test/integration/controllers/auth.spec.js
Labels: bug, Backend, email

#1075 Changed category fields in /courses endpoint
  docs/course/course-schema.yaml
  docs/course/course.yaml
Labels: bug, documentation, Backend

#951 Implement attachment download
  docs/attachments/attachment.yaml
  package-lock.json
  package.json
  src/controllers/attachment.js
  src/routes/attachment.js
  src/services/attachment.js
  src/services/upload.js
  src/test/integration/controllers/attachments.spec.js
  src/test/unit/services/upload.spec.js
  src/utils/pipeDownloadStream.js
Labels: enhancement, Backend

#1365 Renamed swagger docs to kebab case
  docs/admin-invitation/admin-invitation.schema.yaml
  docs/admin-invitation/admin-invitation.yaml
  docs/attachments/attachments.schema.yaml
  docs/auth/auth.schema.yaml
  docs/category/category.schema.yaml
  docs/chat/chat.schema.yaml
  docs/cooperation/cooperation.schema.yaml
  docs/course/course.schema.yaml
  docs/courses-cooperations/courses-cooperations.schema.yaml
  docs/courses-cooperations/courses-cooperations.yaml
  docs/error/error.schema.yaml
  docs/finished-lesson/finished-lesson.schema.yaml
  docs/finished-quiz/finished-quiz.schema.yaml
  docs/finished-quiz/finished-quiz.yaml
  docs/lesson/lesson.schema.yaml
  docs/message/message.schema.yaml
  docs/note/note.schema.yaml
  docs/notifications/notification.schema.yaml
  docs/notifications/notification.yaml
  docs/offer/offer.schema.yaml
  docs/quiz/quiz.schema.yaml
  docs/resources-category/resources-category.schema.yaml
  docs/resources-category/resources-category.yaml
  docs/review/review.schema.yaml
  docs/subject/subject.schema.yaml
  docs/user/user.schema.yaml
Labels: documentation, Backend

#1106 Added subject post request validation
  src/routes/subject.js
  src/test/integration/controllers/category.spec.js
  src/test/integration/controllers/course.spec.js
  src/test/integration/controllers/offer.spec.js
  src/test/integration/controllers/review.spec.js
  src/test/integration/controllers/subject.spec.js
  src/test/integration/controllers/user.spec.js
Labels: Backend, Security

#1366 Fixed internal server error #1000
  src/consts/errors.js
  src/services/location.js
  src/test/integration/controllers/location.spec.js
Labels: bug, Backend

#1367 Update jest
  package-lock.json
  package.json
  src/test/integration/controllers/cooperation.spec.js
  src/test/integration/controllers/finishedQuiz.spec.js
  src/test/integration/controllers/note.spec.js
  src/test/integration/controllers/notification.spec.js
  src/test/integration/controllers/user.spec.js
Labels: Backend, dependency
