Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2025-04, with the labels that each got.

#1261 chore(ci): remove manual trigger from db-backup workflow
  .github/workflows/db-backup.yml
Labels: DevOps

#1264 chore(lint): fix missing .yml support in lint-staged
  package.json
Labels: DevOps

#1262 chore(deps): implement dependabot
  .github/dependabot.yml
Labels: DevOps

#1271 Chore/1234/dependabot
  .github/dependabot.yml
Labels: DevOps

#1258 chore(docs): Fix markdownlint warnings in CONTRIBUTING.md and CONTRIBUTING_UA.md
  CONTRIBUTING.md
  CONTRIBUTING_UA.md
Labels: documentation, DevOps

#1255 Fixed dependencies vulnerabilities
  package-lock.json
  package.json
Labels: Backend, DevOps

#1273 chore(markdownlint): fix Markdown lint issues
  LICENSE
  README.md
Labels: DevOps

#1302 Add sanitizeHtml to remove html tags from req
  package-lock.json
  package.json
  src/controllers/quiz.js
  src/controllers/resourcesCategory.js
Labels: Backend, Security

#1299 Increase test coverage in chat controller
  src/test/integration/controllers/auth.spec.js
  src/test/integration/controllers/chat.spec.js
Labels: Backend, tests

#1309 User controller tests
  src/test/integration/controllers/user.spec.js
Labels: Backend, tests

#1310 Removed hard-coded creds and fixed CWE-798 Vulnerability
  .github/workflows/ci-pr-to-develop-branch.yaml
  src/configs/config.js
  src/test/test-utils.js
  src/utils/testUserAuth.js
Labels: Backend, priority: high, Security

#1300 Added tests for attachments
  src/test/integration/controllers/attachments.spec.js
Labels: Backend, tests

#1301 Remove hardcode api key and url to env file
  src/configs/config.js
  src/services/location.js
Labels: Backend, priority: high, Security

#1308 User service tests
  src/test/unit/services/user.spec.js
Labels: Backend, tests
