Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2025-01, with the labels that each got.

#1102 Fixed incorrect field assignments in Cooperations
  docs/attachments/attachments-schema.yaml
  docs/cooperation/cooperation-schema.yaml
  docs/cooperation/cooperation.yaml
  docs/offer/offer-schema.yaml
  docs/user/user-schema.yaml
Labels: bug, documentation, Backend

#1100 Add validation schema for the body of the PATCH /users/:id endpoint
  src/consts/errors.js
  src/consts/validation.js
  src/middlewares/validation.js
  src/routes/user.js
  src/test/unit/utils/validation/schemaValidators.spec.js
  src/utils/validation/fieldValidators.js
  src/utils/validation/schemaValidators.js
  src/utils/validation/typeHelpers.js
  src/validation/schemas/users/getUserByIdValidationSchema.js
  src/validation/schemas/users/updateUserValidationSchema.js
  src/validation/services/user.js
Labels: enhancement, Backend, Security

#1104 [Swagger] Fixed incorrect field assignments in Messages
  docs/chat/chat.yaml
  docs/message/message-schema.yaml
  docs/message/message.yaml
Labels: bug, documentation, Backend

#1096 Added GET request validation to the endpoint `/users`
  src/routes/user.js
  src/test/integration/controllers/user.spec.js
Labels: Backend, Security

#1101 PATCH request validation to the endpoint `/cooperations/{id}/notes/{id}`
  src/services/note.js
Labels: Backend, Security

#1114 Update workflow with new env
  .github/workflows/main.yaml
Labels: Backend, devOps

#1071 Added migration to delete documents with non-existent author fields
  migrations/20241216212401-remove-documents-with-non-existent-users.js
  src/test/migrations/20241216212401-remove-documents-with-non-existent-users.spec.js
Labels: Backend, Migration

#1080 Created a migration for cooperations
  migrations/20241220213859-delete-old-fields-in-cooperatives-and-add-new-ones.js
  src/test/migrations/20241220213859-delete-old-fields-in-cooperatives-and-add-new-ones.spec.js
Labels: Backend, Migration

#1081 Created a migration for attachments
  migrations/20241222143712-add-resource-type-delete-availability-in-attachments.js
  src/test/migrations/20241222143712-add-resource-type-delete-availability-in-attachments.spec.js
Labels: Backend, Migration

#1093 Lesson Migration
  migrations/20241223082318-delete-avaibility-fields-from-lessons.js
  migrations/20241223103243-fix-and-add-resourceType-to-lessons.js
  src/test/migrations/20241223082318-delete-avaibility-fields-from-lessons.spec.js
  src/test/migrations/20241223103243-fix-and-add-resourceType-to-lessons.spec.js
Labels: Backend, Migration

#1109 Fix Lesson in Swagger documentation
  docs/attachments/attachments-schema.yaml
  docs/lesson/lesson-schema.yaml
  docs/lesson/lesson.yaml
Labels: bug, documentation, Backend

#1110 Fix incorrect field assignments in User
  docs/cooperation/cooperation-schema.yaml
  docs/offer/offer-schema.yaml
  docs/user/user-schema.yaml
  docs/user/user.yaml
Labels: bug, documentation, Backend

#1111 Add safe tests for Subject model
  src/test/integration/models/subject.spec.js
Labels: Backend, tests

#1130 Added migration to remove notifications with non-existent users
  migrations/20250113155310-remove-notification-with-non-existent-users.js
  src/test/migrations/20250113155310-remove-notification-with-non-existent-users.spec.js
Labels: Backend, Migration

#1121 Added PATCH request validation to the endpoint /subjects/{id}
  src/routes/subject.js
  src/test/integration/controllers/subject.spec.js
Labels: Backend, Security

#1115 Added safe tests for Course model
  src/test/integration/models/course.spec.js
Labels: Backend, tests

#1116 Added safe tests for ResourcesCategory model
  src/test/integration/models/resourcesCategory.spec.js
Labels: Backend, tests

#1135 Added safe tests for finishedQuiz model
  src/test/integration/models/finishedQuiz.spec.js
Labels: Backend, tests

#1139 Fixed incorrect schemas in resources categories
  docs/resourcesCategory/resourcesCategory.schema.yaml
  docs/resourcesCategory/resourcesCategory.yaml
Labels: bug, documentation, Backend

#1119 Added safe tests for Token model
  src/test/integration/models/token.spec.js
Labels: Backend, tests

#1122 Added safe tests for FinishedLesson model
  src/test/integration/models/finishedLesson.spec.js
Labels: Backend, tests

#1124 Removed chats with invalid users
  migrations/20241230103249-remove-chats-with-invalid-users.js
  src/test/migrations/20241230103249-remove-chats-with-invalid-users.spec.js
Labels: Backend, Migration

#1126 Added safe tests for Notification model
  src/test/integration/models/notification.spec.js
Labels: Backend, tests

#1153 Add migrations to fix invalid references in resourcesCategories
  migrations/20250123142314-remove-resourcescategories-with-invalid-user-references.js
  src/test/migrations/20250123142314-remove-resourcescategories-with-invalid-user-references.spec.js
  src/utils/mapToId.js
Labels: Backend, Migration

#1133 add updateTotalOffers cronjob
  src/cron-jobs/scheduledCronJobs.js
  src/cron-jobs/updateTotalOffers.js
  src/services/category.js
  src/services/subject.js
  src/test/unit/cron-jobs/scheduledCronJobs.spec.js
  src/test/unit/cron-jobs/updateTotalOffers.spec.js
  src/test/unit/services/category.spec.js
  src/test/unit/services/subject.spec.js
  src/utils/offers/recountOfferAmount.js
Labels: bug, Backend

#1150 Feature/1149/quiz settings migrations
  docs/quiz/quiz-schema.yaml
  docs/quiz/quiz.yaml
  migrations/20250121180446-add-fields-to-quiz.js
  src/consts/validation.js
  src/models/quiz.js
  src/test/integration/controllers/quiz.spec.js
  src/test/migrations/20250121180446-add-fields-to-quiz.spec.js
Labels: Backend, Migration

#1163 Added endpoint for getting a single finished quiz by id
  docs/finishedQuiz/finishedQuiz.yaml
  src/controllers/finishedQuiz.js
  src/routes/finishedQuiz.js
  src/services/finishedQuiz.js
  src/test/integration/controllers/finishedQuiz.spec.js
Labels: Backend, feature

#1105 Enhance needAction field for new cooperation functionality
  migrations/20250114190204-enhance-need-action-in-cooperations.js
  src/consts/validation.js
  src/models/cooperation.js
  src/services/cooperation.js
  src/test/integration/controllers/cooperation.spec.js
  src/test/integration/controllers/note.spec.js
  src/test/migrations/20250114092340-remove-offers-with-non-existing-author.spec.js
  src/test/migrations/20250114190204-enhance-need-action-in-cooperations.spec.js
Labels: Backend, feature, Migration

#1123 Fixed fields mismatch in /course endpoint in POST
  docs/course/course-schema.yaml
  docs/course/course.yaml
Labels: bug, documentation, Backend

#1125 Add safe tests for Offer model
  src/test/integration/models/offer.spec.js
Labels: Backend, tests

#1148 Add migrations to fix invalid references in Cooperation
  migrations/20250124143502-remove-cooperations-with-invalid-references.js
  src/test/migrations/20250124143502-remove-cooperations-with-invalid-references.spec.js
Labels: Backend, Migration

#1173 Fixed migration 20250124143502 tests
  src/test/migrations/20250124143502-remove-cooperations-with-invalid-references.spec.js
Labels: Backend, hotfix

#1162 Update additionalInfo field to meet minimum length requirement in cooperations
  migrations/20250125172611-update-cooperations-additional-info-length.js
  src/test/migrations/20250125172611-update-cooperations-additional-info-length.spec.js
Labels: Backend, Migration

#1166 Fixed incorrect field assignments in Note schema
  docs/note/note-schema.yaml
  docs/note/note.yaml
Labels: bug, Backend

#1154 Safe Tests for Cooperation Model
  src/test/integration/models/cooperation.spec.js
Labels: Backend

#1151 Wrote safe tests for Note Model
  src/models/note.js
  src/test/integration/models/note.spec.js
Labels: Backend, tests

#1167 Fix deleted resources not being removed from cooperations
  src/consts/resourceType.js
  src/services/attachment.js
  src/services/cooperation.js
  src/services/lesson.js
  src/services/quiz.js
  src/services/resourcesCategory.js
  src/test/integration/controllers/attachments.spec.js
  src/test/integration/controllers/lesson.spec.js
  src/test/integration/controllers/quiz.spec.js
Labels: bug, Backend

#1174 Wrote safe tests for Question model
  src/test/integration/models/question.spec.js
Labels: Backend, tests

#1131 Wrote safe tests for message model
  src/test/integration/models/message.spec.js
Labels: Backend, tests

#1132 safe tests for review model
  src/test/integration/models/review.spec.js
Labels: Backend, tests
