Repository ita-social-projects/SpaceToStudy-BackEnd, pull requests merged in 2025-02, with the labels that each got.

#1170 Fix related documents not removed on user deletion
  .eslintrc.json
  src/controllers/attachment.js
  src/services/attachment.js
  src/services/chat.js
  src/services/cooperation.js
  src/services/course.js
  src/services/lesson.js
  src/services/message.js
  src/services/note.js
  src/services/offer.js
  src/services/question.js
  src/services/quiz.js
  src/services/resourcesCategory.js
  src/services/review.js
  src/services/token.js
  src/services/user.js
  src/test/integration/controllers/user.spec.js
Labels: bug, Backend

#1189 Created PATCH endpoint for finished quizzes
  docs/finishedQuiz/finishedQuiz.yaml
  docs/quiz/quiz.yaml
  src/consts/errors.js
  src/controllers/finishedQuiz.js
  src/routes/finishedQuiz.js
  src/services/finishedQuiz.js
  src/test/integration/controllers/finishedQuiz.spec.js
Labels: Backend, feature

#1077 Changed status code to correct value
  docs/user/user.yaml
Labels: bug, documentation, Backend

#1195 Add needAction Logic to PATCH /cooperation Endpoint
  src/models/cooperation.js
  src/services/cooperation.js
  src/test/integration/controllers/cooperation.spec.js
Labels: Backend

#1112 Lessons safe tests
  migrations/20250221121514-remove-documents-with-non-existent-users.js
  src/test/integration/models/lesson.spec.js
  src/test/migrations/20250221121514-remove-documents-with-non-existent-users.spec.js
Labels: Backend, tests

#1120 Attachment safe tests
  src/test/integration/models/attachments.spec.js
Labels: Backend, tests

#1230 chore(ci): improve lint error detection in report generation
  .github/workflows/ci-pr-to-develop-branch.yaml
Labels: DevOps

#1227 chore(Readme): Improve Readme.md
  README.md
Labels: DevOps
